// Generated by website-builder from design-repo/tokens/ (source: https://www.owner.com/?ref=saaspo.com). Tailwind v3. Do not hand-edit; re-run the scrape.
// Values are measured from computed styles; names are heuristic. Nothing here overrides Tailwind's default scales.
// Breakpoints: bp-<px> = min-width, bp-max-<px> = max-width (measured from the site's CSS media queries).
export default {
  corePlugins: { preflight: false }, // the site's own CSS is the reset
  "content": [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx,html}"
  ],
  "theme": {
    "extend": {
      "colors": {
        "neutral-01": "rgb(44,44,44)",
        "neutral-02": "rgb(255,255,255)",
        "neutral-03": "rgba(44,44,44,0.85)",
        "neutral-04": "rgb(0,0,0)",
        "neutral-05": "rgba(44,44,44,0.5)",
        "green-01": "rgb(8,137,36)",
        "neutral-06": "rgb(10,9,9)",
        "neutral-07": "rgb(249,243,237)",
        "neutral-08": "rgb(34,35,35)",
        "neutral-09": "rgb(9,10,11)",
        "neutral-10": "rgba(44,44,44,0.15)",
        "green-02": "rgb(9,68,19)",
        "neutral-11": "rgba(255,255,255,0.85)",
        "neutral-12": "rgb(221,221,221)",
        "neutral-13": "rgb(102,102,102)",
        "neutral-14": "rgb(251,248,245)",
        "neutral-15": "rgba(44,44,44,0.9)",
        "neutral-16": "rgba(0,0,0,0.33)",
        "neutral-17": "rgba(255,255,255,0.1)",
        "red-01": "rgb(255,76,36)",
        "neutral-18": "rgba(255,255,255,0.15)",
        "neutral-19": "rgb(118,118,118)",
        "neutral-20": "rgba(44,44,44,0.3)",
        "orange-01": "rgb(246,238,229)",
        "neutral-21": "rgba(44,44,44,0.05)",
        "green-03": "rgb(194,237,206)",
        "neutral-22": "rgb(51,51,51)",
        "blue-01": "rgb(0,123,255)",
        "neutral-23": "rgb(240,250,255)",
        "neutral-24": "rgba(44,44,44,0.1)",
        "neutral-25": "rgb(254,255,252)",
        "neutral-26": "rgba(0,0,0,0.7)",
        "neutral-27": "rgba(0,0,0,0.15)",
        "green-04": "rgb(55,205,143)",
        "neutral-28": "rgb(242,244,241)",
        "neutral-29": "rgb(238,238,238)",
        "neutral-30": "rgba(10,9,9,0.1)",
        "neutral-31": "rgba(100,100,100,0.2)",
        "neutral-32": "rgb(244,244,244)",
        "neutral-33": "rgba(255,255,255,0.5)",
        "neutral-34": "rgb(249,249,249)",
        "neutral-35": "rgb(9,20,18)",
        "neutral-36": "rgb(197,190,183)",
        "orange-02": "rgb(221,214,206)",
        "blue-02": "rgb(36,90,239)",
        "neutral-37": "rgba(44,44,44,0.16)",
        "neutral-38": "rgb(8,19,18)",
        "neutral-39": "rgb(24,31,31)",
        "neutral-40": "rgba(0,0,0,0.45)",
        "neutral-41": "rgb(224,224,225)",
        "neutral-42": "rgb(179,183,193)",
        "red-02": "rgb(216,0,39)",
        "neutral-43": "rgb(120,122,125)",
        "neutral-44": "rgb(161,163,165)",
        "neutral-45": "rgb(1,1,0)",
        "neutral-46": "rgba(0,0,0,0.16)",
        "blue-03": "rgb(0,81,242)",
        "neutral-47": "rgb(225,225,225)",
        "neutral-48": "rgb(235,235,236)",
        "blue-04": "rgb(24,32,57)",
        "surface-default": "rgb(255,255,255)",
        "surface-alt": "rgb(44,44,44)",
        "surface-inverse": "rgb(44,44,44)",
        "surface-accent": "rgb(9,68,19)",
        "text-primary": "rgb(44,44,44)",
        "text-secondary": "rgb(102,102,102)",
        "text-inverse": "rgb(255,255,255)",
        "text-accent": "rgb(8,137,36)",
        "border-default": "rgb(221,221,221)",
        "accent-primary": "rgb(8,137,36)"
      },
      "spacing": {
        "sp-1": "1px",
        "sp-2": "2px",
        "sp-3_5": "3.5px",
        "sp-7": "7px",
        "sp-8": "8px",
        "sp-8_75": "8.75px",
        "sp-10": "10px",
        "sp-10_5": "10.5px",
        "sp-12": "12px",
        "sp-14": "14px",
        "sp-14_4": "14.4px",
        "sp-15": "15px",
        "sp-16": "16px",
        "sp-20": "20px",
        "sp-21": "21px",
        "sp-24": "24px",
        "sp-25_4117": "25.4117px",
        "sp-28": "28px",
        "sp-32": "32px",
        "sp-35": "35px",
        "sp-40": "40px",
        "sp-55_9999": "55.9999px",
        "sp-64": "64px",
        "sp-104": "104px",
        "gutter": "276px"
      },
      "borderRadius": {
        "r-16": "16px",
        "r-3_5": "3.5px",
        "r-14": "14px",
        "r-8_75": "8.75px",
        "r-32": "32px",
        "r-10": "10px",
        "r-24": "24px",
        "r-10_5": "10.5px",
        "r-8": "8px",
        "r-64": "64px",
        "control": "16px",
        "surface": "3.5px"
      },
      "boxShadow": {
        "e-01": "rgba(44, 44, 44, 0.2) 0px 70px 76px 0px",
        "e-02": "rgba(0, 0, 0, 0.01) 0px 123px 74px 0px, rgba(0, 0, 0, 0.02) 0px 55px 55px 0px, rgba(0, 0, 0, 0.02) 0px 14px 30px 0px",
        "e-03": "rgb(204, 204, 204) 0px 0px 2px 2px",
        "e-04": "rgba(68, 68, 68, 0.11) 0px 7px 20px 0px",
        "e-05": "rgba(0, 0, 0, 0.01) 0px 16px 118.4px 0px, rgba(0, 0, 0, 0.02) 0px 88px 88px 0px, rgba(0, 0, 0, 0.02) 0px 22.4px 48px 0px",
        "e-06": "rgb(222, 222, 222) 0px 0px 0px 1px inset",
        "e-07": "rgba(0, 0, 0, 0.05) 0px 2px 6px 0px",
        "e-08": "rgba(0, 0, 0, 0.15) 0px 2px 12px 0px",
        "elev-default": "rgba(44, 44, 44, 0.2) 0px 70px 76px 0px"
      },
      "fontFamily": {
        "ff-01": [
          "\"STKBureauSans\"",
          "sans-serif"
        ],
        "ff-02": [
          "\"Arial\"",
          "sans-serif"
        ],
        "ff-03": [
          "sans-serif",
          "sans-serif"
        ],
        "ff-04": [
          "\"Helvetica\"",
          "sans-serif"
        ],
        "ff-05": [
          "\"Fragment Mono\"",
          "sans-serif"
        ],
        "ff-06": [
          "\"SuisseIntl\"",
          "sans-serif"
        ],
        "ff-07": [
          "ui-sans-serif",
          "sans-serif"
        ],
        "ff-08": [
          "\"Courier New\"",
          "sans-serif"
        ],
        "display": [
          "\"STKBureauSans\"",
          "sans-serif"
        ],
        "heading": [
          "\"STKBureauSans\"",
          "sans-serif"
        ],
        "body": [
          "\"STKBureauSans\"",
          "sans-serif"
        ],
        "label": [
          "\"STKBureauSans\"",
          "sans-serif"
        ]
      },
      "fontSize": {
        "fs-9_75": "9.75px",
        "fs-10_5": "10.5px",
        "fs-13": "13px",
        "fs-14": "14px",
        "fs-15": "15px",
        "fs-16": "16px",
        "fs-17": "17px",
        "fs-17_5": "17.5px",
        "fs-18": "18px",
        "fs-19_25": "19.25px",
        "fs-20": "20px",
        "fs-22": "22px",
        "fs-24": "24px",
        "fs-30": "30px",
        "fs-32": "32px",
        "fs-48": "48px",
        "fs-64": "64px",
        "fs-80": "80px",
        "display": [
          "48px",
          {
            "lineHeight": "48px",
            "fontWeight": "600"
          }
        ],
        "heading": [
          "22px",
          {
            "lineHeight": "27.94px",
            "fontWeight": "600"
          }
        ],
        "body": [
          "18px",
          {
            "lineHeight": "28.44px",
            "fontWeight": "400"
          }
        ],
        "label": [
          "16px",
          {
            "lineHeight": "20.8px",
            "fontWeight": "400"
          }
        ]
      },
      "transitionDuration": {
        "d-450ms": "0.45s",
        "d-350ms": "0.35s",
        "d-300ms": "0.3s",
        "d-600ms": "0.6s",
        "d-150ms": "0.15s",
        "d-200ms": "0.2s",
        "d-250ms": "0.25s",
        "d-400ms": "0.4s",
        "motion-default": "0.45s"
      },
      "transitionTimingFunction": {
        "ease-01": "cubic-bezier(0.215, 0.61, 0.355, 1)",
        "ease-02": "cubic-bezier(0.38, 0.005, 0.215, 1)",
        "ease-03": "linear",
        "ease-04": "cubic-bezier(0.625, 0.05, 0, 1)",
        "ease-05": "ease",
        "ease-06": "ease-in-out",
        "motion-default": "cubic-bezier(0.215, 0.61, 0.355, 1)"
      },
      "screens": {
        "bp-340": {
          "min": "340px"
        },
        "bp-360": {
          "min": "360px"
        },
        "bp-376": {
          "min": "376px"
        },
        "bp-400": {
          "min": "400px"
        },
        "bp-480": {
          "min": "480px"
        },
        "bp-768": {
          "min": "768px"
        },
        "bp-992": {
          "min": "992px"
        },
        "bp-1060": {
          "min": "1060px"
        },
        "bp-1200": {
          "min": "1200px"
        },
        "bp-1280": {
          "min": "1280px"
        },
        "bp-max-991": {
          "max": "991px"
        },
        "bp-max-767": {
          "max": "767px"
        },
        "bp-max-479": {
          "max": "479px"
        }
      },
      "maxWidth": {
        "content": "1440px"
      }
    }
  },
  "plugins": []
};
